config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'home/index'

    mount Sidekiq::Web => '/sidekiq'

    devise_for :users, controllers: { registrations: 'users/registrations' }

    resources :users, only: %i[update index show]

    namespace :admin do
      resources :comments, only: %i[destroy index]
    end

    resources :orders do
      resources :comments, only: %i[create destroy update]
      get 'export_csv_file', on: :member
    end

    resources :categories

    resources :comments

    root to: 'home#index'

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :order
  has_many :replies, dependent: :delete_all
end

app/controllers/admin/comments_controller.rb
module Admin
  class CommentsController < ApplicationController
    def index
      @comments = Comment.all
    end

    def show
      @comment = Comment.find(params[:id])
    end

    def new
      @comment = Comment.new
    end

    def destroy
      @comment = Comment.find(params[:id])

      @comment.destroy
      flash[:success] = 'Comment deleted'
      redirect_to admin_comments_path
    end

    private

    def comment_params
      params.require(:comment).permit(:text)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_order, only: %i[destroy create]
  def index
    authorize @comment
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def destroy
    @comment = @order.comments.find(params[:id])
    authorize @comment
    @comment.destroy
    flash[:success] = 'Comment deleted'
    redirect_to order_path(@order)
  end

  def create
    @comment = @order.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to order_path(@order)
    else
      render :new
    end
  end

  private

  def find_order
    @order = Order.find(params['order_id'])
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/views/admin/comments/index.html.erb
<h1 class="mb-4">Comments</h1>
<% @comments.each do |comment| %>
  <article class="card">
    <div class="card-body">
      <h4><%= comment.text %></h4>
      <section class="card-text">
        <time datetime="<%= comment.created_at %>">
          <small><%= comment.created_at %></small>
        </time><br>
        <span>User:</span>
        <%= link_to comment.user.name, user_path(comment.user), class: "my-2 my-sm-0" %><br>
        <span>Order:</span>
        <%= link_to comment.order.title, order_path(comment.order), class: "my-2 my-sm-0" %>
      </section>
      <%= link_to 'Delete', admin_comment_path(comment), method: :delete, class: "btn btn-outline-danger my-2 my-sm-0" %>
    </div>
  </article>
<% end %>