config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    get 'home/index'

    mount Sidekiq::Web => '/sidekiq'

    devise_for :users, controllers: { registrations: 'users/registrations' }

    resources :users, only: %i[update index show]

    namespace :admin do
      resources :comments, only: %i[destroy index]
    end

    resources :orders do
      resources :comments, only: %i[create destroy update]
      get 'export_csv_file', on: :member
    end

    resources :categories

    resources :comments

    root to: 'home#index'

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_one_attached :file
  has_one :order_file_report, dependent: :delete
  has_many :comments, dependent: :delete_all

  def formatted_created_at
    created_at.strftime('%Y-%m-%d %H:%M:%S')
  end

  include AASM

  aasm do # default column: aasm_state
    state :open, initial: true
    state :in_progress
    state :completed

    event :take do
      transitions from: :open, to: :in_progress
    end

    event :complete do
      transitions from: :in_progress, to: :completed
    end

    event :cancel do
      transitions from: :in_progress, to: :open
    end
  end

  has_one :category, as: :categorable

  def self.search(query)
    return Order.all if query.blank?

    where('title ILIKE ?', "#{query}%")
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_category, only: [:create]
  def index
    authorize Order
    @orders = if current_user.role == 'user'
                current_user.orders.order(:created_at)
              else
                Order.search(params[:search]).order(:created_at)
              end
  end

  def show
    @order = Order.find(params[:id])
    authorize @order
    @comment = @order.comments.build
    @comments = Comment.where(order_id: @order.id).order(created_at: :desc)
  end

  def new
    authorize Order
    @order = Order.new
    @categories = Category.all.pluck(:title)
  end

  def create
    authorize Order
    @order = Order.new(order_params)
    @order.user = current_user
    @order.category = new_category

    if @order.save
      redirect_to orders_path
      CalculateFileReport.perform_async(@order.id)
    else
      render :new
    end
  end

  def export_csv_file
    csv = GenerateCsv.new(params[:id]).call

    send_data csv[:report], filename: csv[:filename]
  end

  def update
    UpdateOrder.new(params[:id], params[:action_type]).call
    redirect_to orders_path
  end

  def destroy
    @order = Order.find(params[:id])
    authorize @order
    @order.destroy
    flash[:success] = 'Order deleted'
    redirect_to orders_path
  end

  private

  def new_category
    Category.create(title: @category.title)
  end

  def find_category
    @category = Category.find(params['order']['category_id'])
  end

  def order_params
    params.require(:order).permit(:title, :description, :file, :deadline)
  end
end

app/views/orders/_form.html.erb
<%= form_with model: @order do |f| %>
  <div class='mb-3 row'>
    <%= f.label :title, class: 'col-sm-2 col-form-label'%>
    <div class='col-sm-10'>
      <%= f.text_field :title, required: true, minlength: 6, placeholder: 'Title', class: 'form-control' %>
    </div>
  </div>
  <div class='mb-3 row'>
    <%= f.label :description, class: 'col-sm-2 col-form label' %>
    <div class='col-sm-10'>
      <%= f.text_area :description, class: 'form-control my-2'%>
    </div>
    <%= f.label :category, class: 'col-sm-2 col-form label my-2' %>
    <div class='col-sm-10'>
      <%= f.collection_select :category_id, Category.order(:title).uniq { |item| item.title }, :id, :title, class: "form-control" %>
    </div>
    <%= f.label :deadline, class: 'col-sm-2 col-form label my-2' %>
    <div class='col-sm-10'>
      <%= f.datetime_field :deadline %>
    </div>
    <%= f.file_field :file, required: true %>
  </div>
  <%= f.submit 'Create order', class: 'btn btn-outline-success my-2 my-sm-0'%>
</div>
<% end %>

app/views/orders/index.html.erb
<h1 class="mb-4">Orders</h1>
<% @orders.each do |order| %>
  <article class="card">
    <div class="card-body">
      <h4><%= order.title %></h4>
      <span> Status:</span>
      <%= order.aasm_state %>
      <section class="card-text">
        <span> Deadline:</span>
        <time datetime="<%= order.deadline %>">
          <small><%= order.deadline %></small>
        </time>
      </section>
      <%= link_to 'Show', order_path(order), class: "btn btn-outline-success my-2 my-sm-0" %>
      <% if current_user.id == order.user.id || current_user.admin? %>
        <%= link_to 'Delete', order_path(order), method: :delete, class: "btn btn-outline-danger my-2 my-sm-0" %>
      <% end %>
      <% if current_user.id == order.user.id %>
        <% if order.aasm_state == 'open' %>
          <%= link_to 'In progress', order_path(order, action_type: :take), method: :patch, class: "btn btn-outline-info my-2 my-sm-0" %>
        <% end %>
        <% if order.aasm_state == 'in_progress' %>
          <%= link_to 'Reopen', order_path(order, action_type: :cancel), method: :patch, class: "btn btn-outline-info my-2 my-sm-0" %>
          <%= link_to 'Completed', order_path(order, action_type: :complete), method: :patch, class: "btn btn-outline-success my-2 my-sm-0" %>
        <% end %>
      <% end %>
    </div>
  </article>
<% end %>

app/views/orders/new.html.erb
<%= render 'form' %>

app/views/orders/show.html.erb
<h1 class="mb-4"><%= @order.title %> </h1>
<p class="lead my-3">
  <span>Created at: </span>
  <time datetime="<%= @order.formatted_created_at %>">
    <%= @order.formatted_created_at %>
  </time><br>
  <span>Deadline: </span>
  <time datetime="<%= @order.deadline %>">
    <%= @order.deadline %>
  </time><br>
  <span>Description: </span>
  <%= @order.description%><br>
  <span>Status: </span>
  <%= @order.aasm_state%><br>
  <span>Category: </span>
  <%= @order.category.title%><br>
  <br>
  <span>File report: </span><br>
  <span>Symbols count: </span>
  <%= @order.order_file_report&.symbols_count %><br>
  <span>Words count: </span>
  <%= @order.order_file_report&.words_count %><br>
  <span>Symbols exclude spaces count: </span>
  <%= @order.order_file_report&.symbols_exlude_spaces_count%><br>
  <br>
  <%= link_to 'Export csv', export_csv_file_order_path(@order), class: "btn btn-outline-info" %>
  <%= link_to 'Download file', @order.file, class: "btn btn-outline-info"%>
  <%= link_to 'Delete', order_path(@order),  method: :delete, class: "btn btn-outline-danger my-2 my-sm-0" %>
  <div class='mb-3 row'>
    <%= form_with model: [@order, @comment] do |f| %>
      <span>Send comment: </span><br>
      <div class='mb-3 row'>
        <div class='col-sm-10'>
          <%= f.text_area :text, required: true, class: 'form-control my-2'%>
        </div>
      </div>
      <%= f.submit 'Send comment', class: 'btn btn-outline-success my-2 my-sm-0'%>
    </div>
  <% end %>
  <h2 class="mt-5">Comments: </h2>
  <% @comments.each do |comment|%>
    <time datetime="<%= comment.created_at %>">
      <%=comment.created_at%>
    </time>
    <p>
      <%= comment.text %>
    </p>
    <p>
      <%= comment.user.name%>
    </p>
    <%= link_to 'Delete', order_comment_path(@order, comment),  method: :delete, class: "btn btn-outline-danger" %><br>
  <% end %>
</p>